import React from 'react'

function B() {
    return (
        <div>
            <p>ds</p>
            <p>ds</p>
            <p>ds</p>
            <p>ds</p>
            <p>ds</p>
            <p>ds</p>
            <p>ds</p>
            <p>ds</p>
            <p>ds</p>
            <p>ds</p>
            <p>ds</p>
            <p>ds</p>
            <p>ds</p>
            <p>ds</p>
            <p>ds</p>
            <p>ds</p>
            <p>ds</p>
            <p>ds</p>
            <p>ds</p>
            <p>ds</p>
            <p>ds</p>
            <p>ds</p>
            <p>ds</p>
            <p>ds</p>
            <p>ds</p>
            <p>ds</p>
            <p>ds</p>
            <p>ds</p>
            <p>ds</p>
            <p>ds</p>
            <p>ds</p>
            <p>ds</p>
            <p>ds</p>
            <p>ds</p>
            <p>ds</p>
            <p>ds</p>
            <p>ds</p>
            <p>ds</p>
            <p>ds</p>
            <p>ds</p>
            <p>ds</p>
            <p>ds</p>
            <p>ds</p>
            <p>ds</p>
            <p>ds</p>
            <p>ds</p>
            <p>ds</p>
            <p>ds</p>
            <p>ds</p>
            <p>ds</p>
            <p>ds</p>
            <p>ds</p>
            <p>ds</p>
            <p>ds</p>
            <p>ds</p>
            <p>ds</p>
            <p>ds</p>
            <p>ds</p>
            <p>ds</p>
            <p>ds</p>
            <p>ds</p>
            <p>ds</p>
            <p>ds</p>
            <p>ds</p>
            <p>ds</p>
            <p>ds</p>
            <p>ds</p>
            <p>ds</p>
            <p>ds</p>
            <p>ds</p>
            <p>ds</p>
            <p>ds</p>
            <p>ds</p>
            <p>ds</p>
            <p>ds</p>
            <p>ds</p>
        </div>
    )
}

export default B